### ISSUE TITLE
BCF/VCF Output

### ISSUE THREAD

**Issue by reedacartwright** [popgensims/analysis#12]
Write a script that converts the msprime output into a VCF/BCF so it can be incorporated into analyses programs that require VCF/BCF input.

CF. https://tskit.readthedocs.io/en/latest/python-api.html#tskit.TreeSequence.write_vcf

**Comment by jeromekelleher** [comment]
This is easy to do directly in snakemake, the rule would look something like:
```python
rule trees_to_vcf
    input:
        "{filename}.trees"
    output:
       "{filename}.vcf.gz"
    run: 
          ts = tskit.load(input[0])
          with gzip.open(output[0], 'wt') as f:
               ts.write_vcf(f, ploidy=2)
```
We could put the three lines into a ``utilities.py`` module, if we like (which would avoid putting too much code into the snakefile, and also make things more testable).

I think it's a good idea to keep things as simple python functions rather than scripts where we can --- it adds a lot of boilerplate when you need to parse command line args, and the shell is inherently brittle.

**Comment by reedacartwright** [comment]
That makes sense for our purposes.

I do think that we will need to eventually provide a utility script because users of this package might not be comfortable with `snakemake` and they would want to do something like

```bash
convert_to_vcf filename.trees | bcftools ...
```

At least that is my thoughts as a non-python programmer who uses GNU Make a lot for pipeline.

**Comment by jeromekelleher** [comment]
> I do think that we will need to eventually provide a utility script because users of this package might not be comfortable with snakemake and they would want to do something like

This is a key point though: who are the users? What are they using this repo for?

**Comment by reedacartwright** [comment]
Somewhere in this project, whether in `stdpopsim` or `analysis`  or somewhere else, we need scripts that reproducably generate sets of tree sequences because that is one of the big goals of standardizing benchmarks. And then we will need scripts that covert tree sequences to other formats.

**Comment by jeromekelleher** [comment]
The Snakefile + the Docker file *is* reproducible though... This repo is for doing a specific set of analyses, and we're setting it up to be fully reproducible. I don't see what the point of having extra scripts lying around is, other than giving us more stuff to maintain...

**Comment by reedacartwright** [comment]
Continuing via email.
