### ISSUE TITLE
obtain ground truth n_t from multipop models

### ISSUE THREAD

**Issue by petrelharp** [popgensims/analysis#17]
We are running methods to infer "squiggly lines" of N_e(t) from models with more than one population, sometimes with migration. We currently have no implemented method for computing the "truth", which in this case should be the inverse of the coalescence rate. It is in principle straightforward to compute these coalescence rates as a function of time using Markov chain tools; we need a function that takes a demographic model and returns a function of time that gives inverse coalescence rate.

**Comment by andrewkern** [comment]
such an excellent need that this project has exposed

**Comment by jgallowa07** [comment]
I'm happy to do this and implement it into the Snakefile is somebody explains the math. :) @petrelharp?

**Comment by andrewkern** [comment]
closing this down as this is now working and implemented in `msprime`
