### ISSUE TITLE
msmc2 compilation

### ISSUE THREAD

**Issue by andrewkern** [popgensims/analysis#18]
having major headaches with the msmc2. it relies on the d language and static library compiles of gsl.... any ideas about how to force conda to give statically compiled libraries for gsl?

**Comment by andrewkern** [comment]
well here is my update. i'm able to compile msmc IF I don't use the conda supplied d compiler. still working on trying to make the conda package work properly. If not, what we would end up asking the analysis user to do would be to 1) download and install dmd (d-compiler) 2) change the makefile script supplied with msmc (simple enough to write a script to do this) and then 3) do the compilation themselves.

seems messy. how much do we want this to be part of the analysis @popgensims/all ?

**Comment by jeromekelleher** [comment]
Ugh. Is there anyway we could automatically patch the msmc2 Makefile do you think? Conda recipes do this quite a lot --- apply a simple patch to the makefile before compiling to get rid of quirks.

**Comment by andrewkern** [comment]
yes I worked on this late into the evening and figured out how to patch the makefile. will get it on github this morning.
