### ISSUE TITLE
stairwayplot debug

### ISSUE THREAD

**Issue by andrewkern** [popgensims/analysis#28]
I'm unhappy with how the stairwayplot output looks at this point and suspect a bug. tagging @agladstein, @jgallowa07, and @jradrion to help out. let's post progress under this issue.

one thing jared and I just noticed-- the mutation rate defaults in the Snakefile controlling stuff were set incorrectly. we are fixing those to see if we get a difference.

**Comment by jradrion** [comment]
I'll look into this today. If we're strictly talking about the high variance among replicate runs than that is something I experienced as well.

**Comment by andrewkern** [comment]
i'm thinking of the raggedness of the curves. previous estimates that we had done and those shown in the original paper are a good deal smoother when looking at the median of the bootstraps. I wonder if the current code has an issue at the level of bootstrapping?

**Comment by jradrion** [comment]
Gotcha, I'll look into how our bootstrapping affects the smoothness. Can
you point me to your previous estimates?

**Comment by andrewkern** [comment]
ack so in looking at this it looks like our previous estimates were with an unpublished version, v2beta version of the software that must do some posthoc smoothing of the N(t) estimate

**Comment by dschride** [comment]
Been talking to the Kernel about this one offline and I am in agreement with him that the small sample size could be to blame here. It may just be that stairwayplot is inappropriate for smaller samples.

**Comment by jgallowa07** [comment]
@andrewkern @dschride 
[all_estimated_Ne.pdf](https://github.com/popgensims/analysis/files/3233631/all_estimated_Ne.pdf)
This was run with 100 samples and full genomes for stairwayplot and smc++
