### ISSUE TITLE
Wrong msprime version

### ISSUE THREAD

**Issue by Chris1221** [popgensims/analysis#30]
Hello everyone. In trying to replicate the analyses here, it seems as though the version of msprime specified in `requirements.txt` (`0.7.0`) is too old, as the `DemographyDebugger.population_size_history` and `epoch_times` methods are only available in [`2b1d85`](https://github.com/tskit-dev/msprime/commit/2b1d85a54eccaa3d12da9782e83687a9f55f1d1d#diff-3af8c5bda4976d0bd25e9e5754497a74)  from @andrewkern. These are needed in the (`n_t`) `plots.plot_all_ne_estimates` function to correctly add the truth line to the plots. I assume you are all working on the newer versions of `msprime`, but [conda-forge](https://anaconda.org/conda-forge/msprime) and [pypi](https://pypi.org/project/msprime/#files) are only indexing `0.7.0` at the moment. It works fine if installed from source. As it appears that `0.7.1b1` is currently unstable, perhaps putting a note that `msprime` must be installed from github by pip at this point would be sufficient to help others replicate the full analysis.

**Comment by andrewkern** [comment]
yes thanks for pointing this out. very true. @jeromekelleher did the new `DemographyDebugger` stuff make it in to the latest `msprime` release from a few days ago?

**Comment by jeromekelleher** [comment]
Yep, the new code was shipped in the beta on Friday, so we can pin to ``msprime=0.7.1b1`` for now (although it's not available on conda). There's nothing to worry about stability-wise I think,we just have a few wrinkles to work out in the statistical tests for the DTWF model before being 100% confident everything is correct in it. Standard coalescent stuff should be fine.

**Comment by jeromekelleher** [comment]
msprime 0.7.1 has been shipped on PyPI, and the conda packages should be following soon. We can update the requirements here to msprime>=0.7.1 and everything should work fine.

**Comment by jgallowa07** [comment]
FYI the docs specify "NOTE: This requires a bleeding edge install of msprime at the moment." in `n_t` analysis README.

**Comment by Chris1221** [comment]
@jgallowa07 You're right, I apologise for not seeing that. The issue is resolved in any case as soon as msprime is on conda and the requirements are updated. I'll go ahead and close this, as there's not much that needs to be done.
