### ISSUE TITLE
Split up msp_to_stairway_plot, and use functions rather than scripts?

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/analysis#4]
In the current ``msp_to_stairway_plot`` we're calling GNU parallel to run the actual stairway plot invocations. This isn't great because we're not really using Snakemake to its full potential. If these separate jobs existed as rules, we could use snakemake to run them in parallel natively.

Also, I think it would be good to define chunks of functionality as python functions, which we can call from snakemake, rather than scripts that we invoke via an interpreter. For example, the  ``GutenkunstThreePopOutOfAfrica.py`` script could easily be replaced with a function. The advantage of this is we would avoid a lot of command line parsing boilerplate, and also avoid having lots of independent scripts scattered around.

I haven't actually tried doing this though, so I may well be totally wrong; just thinking out loud.

**Comment by andrewkern** [comment]
this is a neat idea and one of the very real advantages of using `snakemake`. if you look in the current `Snakefile` in the Gutenkunst dir I actually am using chunks of python code to import `stdpopsim` and get out things like the mutation rate that are defined. i don't see any reason why we shouldn't at least try out what you are suggesting, but perhaps it means that we should have an analysis module that one would import with the basic functions (e.g. going from tree sequences to stairwayplot input file formats)?

**Comment by andrewkern** [comment]
I'm going to close this issue. Think we are set here. Can always reopen later if need be.
