### ISSUE TITLE
GenericConstantSize model breaks coal_rate plotting

### ISSUE THREAD

**Issue by andrewkern** [popgensims/analysis#40]
https://github.com/popgensims/analysis/blob/607772593ef8042a18d72dea2098e4d55f87dcc0/n_t/plots.py#L117

going to dig in here, but out of the box the `GenericConstantSize` model breaks the current implementation of the coal_rate trajectory stuff. my quick guess is that having a single epoch in the `DemographyDebugger` is breaking things. @petrelharp did you write this with @jgallowa07?

**Comment by petrelharp** [comment]
yep; I'll have a look.

**Comment by andrewkern** [comment]
just patching this currently on the `Snakefile` side of things. that should be all it takes I think
