### ISSUE TITLE
Human genome results for N(t) under constant population size

### ISSUE THREAD

**Issue by andrewkern** [popgensims/analysis#41]
the new Generic model classes that were created in `stdpopsim` give us the opportunity to test how well things should work under a variety of very simple models. Below I have results from simulated human genomes (3 reps) using the Hapmap genetic map. As you can see, in this case stairway plot does an excellent job, while the smc based methods perform less well. Even so every method is within two-fold of the true value (N=10000). 

thoughts? if people are happy with this we can keep moving

<img width="843" alt="Untitled" src="https://user-images.githubusercontent.com/7674197/62661086-d2e9a700-b924-11e9-878d-b6615775648d.png">

**Comment by dortegadelv** [comment]
I also got underestimated Ne values using SMC++ under the Gutenkunst model using two populations and running one single chromosome ( https://github.com/popgensims/analysis/pull/39 ), so it is good to see that results are pointing in the same direction.

**Comment by andrewkern** [comment]
i think the next generic case to write is a simple IM model. it will be good to run the two population inference pipeline on that one as well @dortegadelv  

A question that @jeromekelleher and I were chatting about this week is what would a generic parameterization of the IM model look like? N_1 = N_2 = N_A with symmetric migration?

**Comment by dortegadelv** [comment]
N_1 = N_2 = N_A with symmetric migration sounds good to me. Can we also get am IM model with no migration to check the effect of migration on all parameter estimates?

**Comment by petrelharp** [comment]
This is great, thanks for putting this in there, @andrewkern. Probably the difference between the methods (why stairwayplot looks better) has to do with how they regularize. Agree about the IM model.

**Comment by fbaumdicker** [comment]
I have missed many of the last calls but it is great to see generic models back on the agenda. In my opinion, this is the most valuable aspect of the project. The figure is cool.
Regarding the symmetric island models, we have recently used the Gutenkunst out of Africa model and a symmetric island model with five islands to test our method.
We used N_1 = ... = N_5 and symmetric constant migration rates above zero.
We didn't use an ancestral population, so I would vote for:
N_1 = N_2 with symmetric migration without an ancestral population. However, that would require migration rates > 0.
We set mutation rates such that the expected number of SNPs is as desired and the recombination rate to ten times the mutation rate.

**Comment by RyanGutenkunst** [comment]
> N_1 = N_2 = N_A with symmetric migration sounds good to me. Can we also get am IM model with no migration to check the effect of migration on all parameter estimates?

Note that these one-pop methods should all treat an IM model with no migration as exactly equivalent to a one-population model. If they don't, that suggests some flaw in our simulations.

**Comment by andrewkern** [comment]
closing as this is obsolete
