### ISSUE TITLE
'true' parameters from mean coal time method

### ISSUE THREAD

**Issue by ckyriazis** [popgensims/analysis#45]
I added the estimates for the 'true' pop size from @petrelharp 's mean_coalescence_time method to the drosophila and human plots earlier today. It looks like the method is essentially averaging out over the two epochs such that the estimated pop sizes for N1 and N2 are intermediate with Na. 

@andrewkern suggested during the call yesterday that we should be able to integrate over each epoch but I'm not exactly sure how to go about doing that. Kirk suggested possibly instead using P(2 samples coalesce more recent than the split) as a way to get at the 'true' N. 

How should we proceed here?

![estimates_N_tdiv_dadi_fsc](https://user-images.githubusercontent.com/11757173/64739763-e1892800-d4a7-11e9-93d1-e37de6b36009.png)
 

![estimates_N_tdiv_dadi_fsc](https://user-images.githubusercontent.com/11757173/64739775-e8179f80-d4a7-11e9-84c5-47dcc34c0617.png)

**Comment by petrelharp** [comment]
I think that both modern Ne and mean coalescence time are good things to compare against. I like Kirk's suggestion, IIUC, it's to find the N so that
```
 P(pair hasn't yet coalesced before the split) = exp(- T / (2N))
so
 N = - (2/T) * log(P(not coalesced at split))
```
... where T is the time of the split? You can get this probability of not-yet-coalesced using [this method](https://msprime.readthedocs.io/en/stable/api.html#msprime.DemographyDebugger.coalescence_rate_trajectory) of the Demography Debugger.

**Comment by petrelharp** [comment]
Also, these plots are hard to read: maybe have the "refernce points" using a different point type?

**Comment by ckyriazis** [comment]
Thanks for the input @petrelharp - I'll look into that method.

And apologies about the plots! I'll have better looking plots by the time we finalize the manuscript, but for now am a bit limited by my lack of experience with seaborn...

**Comment by petrelharp** [comment]
> And apologies about the plots! 

No worries; they look like all my early draft plots also.

Ping me if the coal prob method isn't clear.

**Comment by ckyriazis** [comment]
Here are the results with the p(not coal) approach. Looks like it works pretty well. 
![estimates_N_tdiv_dadi_fsc](https://user-images.githubusercontent.com/11757173/64897244-99990b00-d637-11e9-9363-0a85537269ad.png)

![estimates_N_tdiv_dadi_fsc](https://user-images.githubusercontent.com/11757173/64897255-a0278280-d637-11e9-9954-a8d81548c49c.png)

**Comment by petrelharp** [comment]
Nice. Can you say breifly what's being plotted? Like, why are there two green dots above Na (shouldn't there just be one "truth")?

**Comment by ckyriazis** [comment]
Ahh yea sorry I explained this in our call but its totally unclear if you werent there...the two green dots for Na in the drosophila model (top) are simply the two different ancestral sizes in the Li & Stephan model (see below). 
![image](https://user-images.githubusercontent.com/11757173/64898741-2f836480-d63d-11e9-9335-5f60d4c03a55.png)

So the takeaway is that Na1 in that model has a much stronger influence on the inferred value than Na0. Let me know if you have any other ideas for how to get the 'truth' for the ancestral population in this case.

**Comment by ckyriazis** [comment]
closing this.
